#!/usr/bin/env python3
from modules.boot_performance_total import main
from modules.shell_script_launcher import run_shell_script


if __name__ == '__main__':
    command = ''
    while command not in ['0', '1', '2']:
        command = input(
          'To update press 1\
          \nTo check boot performance press 2\
          \nTo close press 0\
          \n-> Choosed Option: '
        )

    if command == '1':
        print('Starting shell script...')
        run_shell_script('shell-script/updater')
    elif command == '2':
        print('Calculating...')
        main()
    elif command == '0':
        print('Exiting...')
        exit()

else:
    print('This is a script, not a module!')
