#!/usr/bin/env python3
from modules.boot_performance_total import calculate
from modules.shell_script_launcher import run_shell_script
from modules.color import colors



if __name__ == '__main__':
    c = colors()
    command = ''

    while command not in ['0', '1', '2']:
        command = input(
          'To update press 1\
          \nTo check boot performance press 2\
          \nTo close press 0\
          \n-> Choosed Option: '
        )
        
        if command not in ['0', '1', '2']:
            print(f'\n{c.YE}{c.BLD}Please press an valid option!{c.END}\n')

    if command == '1':
        print('Starting shell script...')
        print(
            '\nYou can find logs for update',
            f'{c.RE}errors{c.END} in {c.BL}',
            f'file:///tmp/.update-errors.log{c.END}'
        )
        run_shell_script('shell-script/updater')
    
    elif command == '2':
        print('Calculating...\n')
        calculate()
    
    elif command == '0':
        print('Exiting...')
        exit()
    

else:
    print('This is a script, not a module!')
